dlearn/course/api/urls.py
from django.urls import path

from .views import (
    CourseAPIView, 
    CourseListAPIView, 
    CourseUpdateAPIView,
    JoinCourseAPIVIew,
    LeaveCourseAPIView
)


app_name = 'course_api'

urlpatterns = [
    path('', CourseAPIView.as_view(), name='course'),
    path('update/', CourseUpdateAPIView.as_view(), name='update'),
    path('join/', JoinCourseAPIVIew.as_view(), name='join'),
    path('leave/', LeaveCourseAPIView.as_view(), name='leave'),
    path('list/', CourseListAPIView.as_view(), name='course_list'),
]

dlearn/course/urls.py
from django.urls import path

from .views import (
    CourseCreateView,
    CourseJoinView,
    CourseDetailView,
    CourseDeleteView,
    CourseUpdateView,
    UserCourseView,
    LeaveCourseView,
    KickUserView
)


app_name = 'course'
urlpatterns = [
    path('create/', CourseCreateView.as_view(), name='create'),
    path('join/', CourseJoinView.as_view(), name='join'),
    path('<int:course_id>/', CourseDetailView.as_view(), name='detail'),
    path('<int:course_id>/delete/', CourseDeleteView.as_view(), name='delete'),
    path('<int:course_id>/settings/', CourseUpdateView.as_view(), name='settings'),
    path('<int:course_id>/users/', UserCourseView.as_view(), name='users'),
    path('<int:course_id>/kick_user/<int:user_id>/', KickUserView.as_view(), name='kick_user'),
    path('<int:course_id>/leave/', LeaveCourseView.as_view(), name='leave'),
]

dlearn/dlearn/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('course/', include('course.urls')),
    path('course/', include('task.urls')),
    path('course/', include('quiz.urls')),
    path('', include('homepage.urls')),
    # path('__debug__/', include('debug_toolbar.urls'))
]

api_urlpatterns = [
    path('auth/', include('authentication.api.urls')),
    path('course/', include('course.api.urls')),
    path('task/', include('task.api.urls')),
    path('quiz/', include('quiz.api.urls')),
]

urlpatterns += [
    path('api/1.0/', include(api_urlpatterns)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dlearn/quiz/urls.py
from django.urls import path

from .views import QuizCreateView, QuizDetailView, UserDetailView


app_name = 'quiz'
urlpatterns = [
    path('<int:course_id>/task/<int:task_id>/create-quiz/', view=QuizCreateView.as_view(), name='create'),
    path('<int:course_id>/task/<int:task_id>/quiz/', view=QuizDetailView.as_view(), name='detail'),
    path('<int:course_id>/task/<int:task_id>/quiz/user-detail/<int:user_id>/', view=UserDetailView.as_view(), name='user_detail')
]

dlearn/task/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import (
    TaskCreateView,
    TaskDetailView,
    TaskDeleteView,
    TaskUpdateView,
    DeleteOwnerFileView,
    DeleteUserFileView,
    AddUserFilesView,
    UserFilesListView,
    UserRatingView
)


app_name = 'task'
urlpatterns = [
    path('<int:course_id>/create-task/', login_required(TaskCreateView.as_view()), name='create'),
    path('<int:course_id>/task/<int:task_id>/', login_required(TaskDetailView.as_view()), name='detail'),
    path('<int:course_id>/task/<int:task_id>/delete/', login_required(TaskDeleteView.as_view()), name='delete'),
    path('<int:course_id>/task/<int:task_id>/update/', login_required(TaskUpdateView.as_view()), name='update'),
    path('<int:course_id>/task/<int:task_id>/delete-owner-file/<int:file_id>/', 
         login_required(DeleteOwnerFileView.as_view()),
         name='delete_owner_file'
    ),
    path('<int:course_id>/task/<int:task_id>/delete-user-file/<int:file_id>/',
         login_required(DeleteUserFileView.as_view()),
         name='delete_user_file'
    ),
    path('<int:course_id>/task/<int:task_id>/add-files/', login_required(AddUserFilesView.as_view()), name='add_files'),
    path('<int:course_id>/task/<int:task_id>/user-files/', login_required(UserFilesListView.as_view()), name='user_files'),
    path('<int:course_id>/task/<int:task_id>/user-rating/', login_required(UserRatingView.as_view()), name='user_rating')
]

dlearn/course/forms.py
from pathlib import WindowsPath
from django import forms
from django.forms.utils import ErrorList
from django.utils.translation import gettext_lazy as _

from authentication.validators import is_password_valid
from authentication.errors import ErrorMessages
from .models import Course


class CourseCreateForm(forms.ModelForm):
    """
    A form for course creating.
    """
    confirm_password = forms.CharField(max_length=20, min_length=6, widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Повторіть Пароль'}))
    
    class Meta:
        model = Course
        fields = [
            'name',
            'password',
            'group_name',
            'join_code',
            'image'
        ]
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control form-control course-form-input',
                'placeholder': 'Назва Курсу',
                'maxlength': '128'
            }),
            'password': forms.PasswordInput(attrs={
                'class': 'form-control',
                'placeholder': 'Пароль',
                'minlength': '6',
                'maxlength': '20'
            }),
            'group_name': forms.TextInput(attrs={
                'class': 'form-control course-form-input',
                'placeholder': 'Група',
                'maxlength': '60',
            }),
            'join_code': forms.TextInput(attrs={
                'class': 'form-control course-form-input',
                'placeholder': 'Код Долучення',
                'minlength': '5',
                'maxlength': '20',
            }),
            'image': forms.FileInput(attrs={
                'class': 'form-control',
                'placeholder': 'Зображення Курсу',
            })
        }
        
    def clean(self):
        """Redefined clean method to validate password and cofirm_password

        Raises:
            forms.ValidationError: 
                - raise if password and confirm password don't match
                - raise of password doesn't contain at least 1 character and at least 1 number
        """
        cleaned_data = super(CourseCreateForm, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        
        if not is_password_valid(password):
            raise forms.ValidationError(ErrorMessages.PASSWORD_VALIDATION_ERROR)
        if password != confirm_password:
            errors = self._errors.setdefault('password', ErrorList())
            errors.append(ErrorMessages.PASSWORD_NOT_MATCH_ERROR)
            raise forms.ValidationError(ErrorMessages.PASSWORD_NOT_MATCH_ERROR)
        
    def save(self, commit=True):
        """Redefined save method to set hashed course password

        Args:
            commit (bool, optional): Saves the model if commit=True. Defaults to True.

        Returns:
            Course: The new created course
        """
        course = super(CourseCreateForm, self).save(commit=False)
        course.set_password(self.cleaned_data['password'])
        
        if commit:
            course.save()
        return course


class CourseUpdateForm(forms.ModelForm):
    """
    A form for course updating.
    """
    password = forms.CharField(required=False,
                               min_length=6,
                               max_length=20,
                               widget=forms.PasswordInput(attrs={
                                   'class': 'form-control course-form-input',
                                   'placeholder': 'Новий пароль'
                               }))
    confirm_password = forms.CharField( min_length=6, 
                                        max_length=20, 
                                        required=False, 
                                        widget=forms.PasswordInput(attrs={
                                            'class': 'form-control course-form-input', 
                                            'placeholder': 'Повторіть пароль'
                                        }))
    
    class Meta:
        model = Course
        fields = [
            'name',
            'group_name',
            'join_code',
            'image',
        ]
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control form-control course-form-input',
                'placeholder': 'Назва Курсу',
                'maxlength': '128'
            }),
            'group_name': forms.TextInput(attrs={
                'class': 'form-control course-form-input',
                'placeholder': 'Група',
                'maxlength': '60',
            }),
            'join_code': forms.TextInput(attrs={
                'class': 'form-control course-form-input',
                'placeholder': 'Код Долучення',
                'minlength': '5',
                'maxlength': '20',
            }),
            'image': forms.FileInput(attrs={
                'class': 'form-control',
                'placeholder': 'Зображення Курсу',
            })
        }
    
    def clean(self):
        cleaned_data = super(CourseUpdateForm, self).clean()

        if cleaned_data['password'] != cleaned_data['confirm_password']:
            errors = self._errors.setdefault('password', ErrorList())
            errors.append(ErrorMessages.PASSWORD_NOT_MATCH_ERROR)
            raise forms.ValidationError(ErrorMessages.PASSWORD_NOT_MATCH_ERROR)
        if not is_password_valid(cleaned_data['password']):
            errors = self._errors.setdefault('password', ErrorList())
            errors.append(ErrorMessages.PASSWORD_VALIDATION_ERROR)
            raise forms.ValidationError(ErrorMessages.PASSWORD_VALIDATION_ERROR)


class CourseJoinForm(forms.ModelForm):
    """
    A form for joining to a course.
    """
    class Meta:
        model = Course
        fields = [
            'join_code',
            'password'
        ]
        widgets = {
            'password': forms.PasswordInput(attrs={
                'class': 'form-control form-input',
                'placeholder': 'Пароль Курсу'
            }),
            'join_code': forms.TextInput(attrs={
                'class': 'form-control form-input',
                'placeholder': 'Код Долучення'
            })
        }

dlearn/course/api/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from rest_framework.status import HTTP_201_CREATED, HTTP_200_OK, HTTP_400_BAD_REQUEST, HTTP_403_FORBIDDEN, HTTP_404_NOT_FOUND

from django.shortcuts import get_object_or_404

from .serializers import CourseSerializer, CourseUpdateSerializer
from .helpers import get_course_id_error_message_if_any

from ..models import Course


class CourseAPIView(APIView):
    permission_classes = (IsAuthenticated,)
    serializer_class = CourseSerializer

    def get(self, request):
        course_id = request.data.get('id')

        if course_id:
            course = get_object_or_404(Course, id=int(course_id))
            serializer = self.serializer_class(instance=course)
            return Response(serializer.data, status=HTTP_200_OK)

        return Response('id is required', status=HTTP_400_BAD_REQUEST)

    def post(self, request):
        confirm_password = request.data.pop('confirm_password')
        serializer = self.serializer_class(data=request.data, 
                                           context={
                                               'owner': request.user,
                                               'confirm_password': confirm_password
                                            })

        if serializer.is_valid(raise_exception=True):
            course = serializer.save()
            serializer = self.serializer_class(instance=course)
            return Response(serializer.data, status=HTTP_201_CREATED)


class CourseListAPIView(APIView):
    queryset = Course.objects.all()
    permission_classes = (IsAuthenticated,)
    serializer_class = CourseSerializer

    def get(self, request):
        owned_courses = Course.objects.filter(owner=request.user)
        joined_courses = request.user.courses.all()

        owned_serializer = self.serializer_class(instance=owned_courses, many=True)
        joined_serializer = self.serializer_class(instance=joined_courses, many=True)

        response = {
            'owned_courses': owned_serializer.data,
            'joined_courses': joined_serializer.data
        }

        return Response(response, status=HTTP_200_OK)


class CourseUpdateAPIView(APIView):
    permission_classes = (IsAuthenticated,)
    serializer_class = CourseUpdateSerializer
    
    def patch(self, request):
        course_id = request.data.get('id')
        message = get_course_id_error_message_if_any(course_id)
        
        if message:
            return Response(message, status=HTTP_400_BAD_REQUEST)

        course = get_object_or_404(Course, id=int(course_id))

        if course.owner != request.user:
            return Response(status=HTTP_403_FORBIDDEN)
        
        serializer = self.serializer_class(data=request.data)
        
        if serializer.is_valid(raise_exception=True):
            course = serializer.update(course, serializer.validated_data)
            return Response(CourseSerializer(instance=course).data, status=HTTP_200_OK)

        return Response(status=HTTP_400_BAD_REQUEST)


class JoinCourseAPIVIew(APIView):
    permission_classes = (IsAuthenticated,)

    def post(self, request):
        course_id = request.data.get('id')
        message = get_course_id_error_message_if_any(course_id)
        
        if message:
            return Response(message, status=HTTP_400_BAD_REQUEST)
        
        course = Course.objects.get(id=course_id)
        if course.users.contains(request.user):
            return Response(f'User {request.user} is already joined this course.', status=HTTP_403_FORBIDDEN)

        course.users.add(request.user)
        return Response(CourseSerializer(instance=course).data, status=HTTP_200_OK)


class LeaveCourseAPIView(APIView):
    permission_classes = (IsAuthenticated,)
    
    def post(self, request):
        course_id = request.data.get('id')
        message = get_course_id_error_message_if_any(course_id)
        
        if message:
            return Response(message, status=HTTP_400_BAD_REQUEST)

        course = Course.objects.get(id=course_id)
        if not course.users.contains(request.user):
            return Response(f'User {request.user} is not a member of this course.', status=HTTP_403_FORBIDDEN)
        
        course.users.remove(request.user)
        return Response(status=HTTP_200_OK)

dlearn/course/templates/course/course_users.html
{% extends 'homepage/_base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'course/style.css' %}">
{% endblock styles %}

{% block content %}

<div class="container users-container">
    <div class="row">
        <h2 class="course-users-header text-center">Рейтинг студентів</h2>
    </div>
    <div class="row text-center">
        <table class="users-table">
            <tr class="headers-row">
                <th rowspan="2" class="table-counter"></th>
                <th rowspan="2">Ім'я та Прізвище</th>
                {% for task in tasks %}
                    <th colspan="2">{{ task.name }}</th>
                {% endfor %}
                <th rowspan="2"></th>
            </tr>
            <tr>
                {% for task in tasks %}
                    <th>Завдання</th>
                    <th>Тести</th>
                {% endfor %}
            </tr>
            {% for user, marks in users_marks.items %}
                <tr class="table-row">
                    <td class="table-counter">{{ forloop.counter }}</td>
                    <td class="table-username">{{ user.first_name }} {{ user.last_name }}</td>
                    {% for mark in marks %}
                        {% if mark is None %}
                            <td>-</td>
                        {% else %}
                            <td>{{ mark }}</td>
                        {% endif %}
                    {% endfor %}
                    <td class="button-data">
                        <form action="{% url 'course:kick_user' course.id user.id %}" method="POST">
                            {% csrf_token %}
                            <input type="submit" class="delete-user-btn" value="Видалити">
                        </form>
                    </td>
                </tr>
            {% empty %}
                <tr class="empty-row">
                    <td>_</td>
                    <td>_</td>
                    <td>_</td>
                </tr>
            {% endfor %}
        </table>
    </div>
</div>

{% endblock content %}

dlearn/course/templates/course/create.html
{% extends 'homepage/_base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'course/style.css' %}">
{% endblock styles %}

{% block content %}


<div class="container">
    
    <div class="form-group course-form">
        {% block course_form %}
        <form action="{% url 'course:create' %}" enctype="multipart/form-data" method="POST">
        {% endblock course_form %}
            {% csrf_token %}
            <div class="form-group text-center">
                
                <h3 class="text-center course-create-header">{% block course_header %}Створіть ваш курс{% endblock course_header %}</h3>
                
            </div>
            <div class="form-group row">
                <div class="form-group col-md-4 text-center">
                    <img class="course-form-image" id="form_image" {% block image_src %}src="https://simonpaulhair.co.uk/wp-content/uploads/2014/03/320x320.gif"{% endblock image_src %} width="320" height="320">
                </div>
                <div class="form-group col-md-8 image-right-col">
                    <div class="form-group row">
                        <img src="{% static 'homepage/open-iconic/svg/book.svg' %}" class="form-svg book-svg">
                        {{ form.name }}
                    </div>
                    <div class="form-group row">
                        <img src="{% static 'homepage/open-iconic/svg/people.svg' %}" class="form-svg people-svg">
                        {{ form.group_name }}
                    </div>
                    <div class="form-group row">
                        <img src="{% static 'homepage/open-iconic/svg/key.svg' %}" class="form-svg key-svg">
                        {{ form.join_code }}
                        {% if form.errors.join_code %}
                            <small class="form-error">Курс з таким кодом вже існує</small>
                        {% endif %}
                    </div>
                    <div class="row course-line-draw"></div>
                    <div class="form-group row">
                        <label id="image-input-label">Оберіть зображення курсу: </label>
                        {{ form.image }}
                    </div>
                </div>
            </div>
            <div class="row course-line-draw line-draw-2"></div>
            <div class="form-group row">
                <div class="form-group col-md-6">
                    <img src="{% static 'homepage/open-iconic/svg/lock-locked.svg' %}" class="form-svg course-lock-svg">
                    {{ form.password }}
                    <small class="form-password-error">{{ form.errors.password }}</small>
                </div>
                <div class="form-group col-md-6">
                    <img src="{% static 'homepage/open-iconic/svg/lock-locked.svg' %}" class="form-svg course-lock-svg">
                    {{ form.confirm_password }}
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    
                    <input class="form-control course-create-button" type="submit" value={% block course_button %}"Створити курс"{% endblock course_button %}>
                    
                </div>
            </div>
        </form>
    </div>
</div>
<script>
    const fileSelector = document.getElementById('id_image');

    fileSelector.addEventListener('change', (event) => {
        const fileList = event.target.files;
        const reader = new FileReader();

        reader.readAsDataURL(fileList[0])

        reader.onload = function(event) {
            document.getElementById('form_image').src = event.target.result;
        };
    });
</script>
{% endblock content %}

dlearn/course/templates/course/detail.html
{% extends 'homepage/_base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'course/style.css' %}">
{% endblock %}

{% block content %}

<div class="container course-container">
    <div class="row head-div">
        <div class="col-md-3">
            {% if course.image %}
                <img src="{{ course.image.url }}" class="course-image" width="280" height="280">
            {% else %}
                <img src="{% static 'course/images/default_image.png' %}" class="course-image" width="280" height="280">
            {% endif %}
        </div>
        <div class="col text-center">
            <h2 class="course-header">{{ course.name }}</h2>
            <div class="row">
                <div class="col-md-5">
                    <h5 class="course-owner"><span class="course-owner-label">Викладач:</span> {{ course.owner.first_name }} {{ course.owner.last_name }}</h5>
                </div>
                <div class="col-md-6">
                    <h5 class="course-group">
                        <span class="course-group-label">Група:</span>
                        {% if course.group_name %}{{ course.group_name }}
                        {% else %} відсутня
                        {% endif %}
                    </h5>
                </div>
            </div>

            {% if is_owner %}
            <div class="row course-buttons-row">
                <div class="col course-button-col">
                    <a href="{% url 'course:settings' course.id %}"><button class="course-button">Налаштування</button></a>
                </div>
                <div class="col course-button-col">
                    <a href="{% url 'task:create' course.id %}"><button class="course-button">Додати Завдання</button></a>
                </div>
                <div class="col course-button-col">
                    <a href="{% url 'course:users' course.id %}"><button class="course-button">Рейтинг</button></a>
                </div>
                <div class="col course-button-col">
                    <form action="{% url 'course:delete' course.id %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="is_owner" value="{{ is_owner }}">
                        <input type="submit" class="course-leave-button course-button" value="Видалити Курс">
                    </form>
                </div>
            </div>
            {% else %}
            <div class="row">
                <div class="col">
                    <form action="{% url 'course:leave' course.id %}" method="POST" class="user-leave-form">
                        {% csrf_token %}
                        <input type="submit" class="course-leave-button course-button" value="Покинути Курс">
                    </form>
                </div>
            </div>
            {% endif %}

        </div>
    </div>
    
    <!-- Task headers -->
    <div class="row">
        <div class="col-md-4">
            <h3 class="course-task-header">Назва</h3>
        </div>
        <div class="col-md-4">
            <h3 class="course-task-header">Час публікації</h3>
        </div>
        <div class="col-md-4">
            <h3 class="course-task-header">Термін здачі</h3>
        </div>
    </div>

    <!-- tasks -->
    {% for task in tasks %}
    <a href="{% url 'task:detail' course.id task.id %}" class="course-task-link">
        <div class="row task-row">
            <div class="col-md-4">
                <h4 class="course-task-name">{{ task.name }}</h4>
            </div>
            <div class="col-md-4 timespan-div">
                <span>{{ task.created_at }}</span> 
            </div>
            <div class="col-md-4 timespan-div">
                {% if task.do_up_to %}<span>{{ task.do_up_to }}</span>
                {% else %} <span>Не обмежено</span>
                {% endif %}
            </div>
        </div>
    </a>
    {% endfor %}

</div>
{% endblock content %}

dlearn/course/templates/course/join.html
{% load static %}

<div class="form-group">
    <h3 class="text-center login-form-header">Додайте Курс</h3>
    <form action="{% url 'course:join' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <img src="{% static 'homepage/open-iconic/svg/key.svg' %}" class="form-svg join-key-svg">{{ join_form.join_code }}
        </div>
        <div class="form-group">
            <img src="{% static 'homepage/open-iconic/svg/lock-locked.svg' %}" class="form-svg join-lock-svg">{{ join_form.password }}
            <small class="form-error">{{ join_form.join_code.errors }}</small>
        </div>
        <div class="form-group">
            <input class="form-control form-btn" type="submit" value="Приєднатися">
        </div>
        <div class="text-center form-bottom-text">
            <small>Хочете власний курс? <a href="{% url 'course:create' %}" class="form-link">Створіть зараз</a></small>
        </div>
    </form>
</div>

dlearn/course/templates/course/settings.html
{% extends 'course/create.html' %}
{% load static %}

<!-- This page extends from course create form and changes 3 small blocks -->

{% block course_header %}Редагування курсу{% endblock course_header %}

{% block course_form %}
    <form action={% url 'course:settings' course.id %} method="POST" enctype="multipart/form-data">
{% endblock course_form %}

{% block image_src %}
    {% if course.image %}
        src="{{ course.image.url }}"
    {% else %}
        src="{% static 'course/images/default_image.png' %}"
    {% endif %}
{% endblock image_src %}

{% block course_button %}"Зберегти зміни"{% endblock course_button %}