dlearn/authentication/api/urls.py
from django.urls import path

from .views import ReceiveAuthToken


app_name = 'auth_api'

urlpatterns = [
    path('token/', ReceiveAuthToken.as_view(), name='token'),
]

dlearn/authentication/urls.py
from django.urls import path

from .views import RegisterView, LoginView, LogoutView


app_name = 'authentication'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
]

dlearn/dlearn/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('course/', include('course.urls')),
    path('course/', include('task.urls')),
    path('course/', include('quiz.urls')),
    path('', include('homepage.urls')),
    # path('__debug__/', include('debug_toolbar.urls'))
]

api_urlpatterns = [
    path('auth/', include('authentication.api.urls')),
    path('course/', include('course.api.urls')),
    path('task/', include('task.api.urls')),
    path('quiz/', include('quiz.api.urls')),
]

urlpatterns += [
    path('api/1.0/', include(api_urlpatterns)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dlearn/quiz/urls.py
from django.urls import path

from .views import QuizCreateView, QuizDetailView, UserDetailView


app_name = 'quiz'
urlpatterns = [
    path('<int:course_id>/task/<int:task_id>/create-quiz/', view=QuizCreateView.as_view(), name='create'),
    path('<int:course_id>/task/<int:task_id>/quiz/', view=QuizDetailView.as_view(), name='detail'),
    path('<int:course_id>/task/<int:task_id>/quiz/user-detail/<int:user_id>/', view=UserDetailView.as_view(), name='user_detail')
]

dlearn/authentication/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.core.validators import validate_email
from django.db import models
from django.utils.translation import gettext_lazy as _

from .managers import UserManager


class CustomUser(AbstractBaseUser, PermissionsMixin):
    """
        This class represents a basic user.\n
        Attributes:
        ----------
        param email: Describes the email of the user
        type email: str, unique, max_length=40
        param password: Describes the password of the user
        type password: str, max_length=255
        param first_name: Describes the first name of the user
        type first_name: str, max_length=30, null=True
        param last_name: Describes the last name of the user
        type last_name: str, max_length=30, null=True
        param created_at: Describes the date when the user was created. Can't be changed
        type created_at: int (timestamp)
        param role: Describes the role of the user
        type role: int, default=0
    """
    email = models.EmailField(verbose_name=_('Email'), max_length=40, unique=True, validators=[validate_email])
    password = models.CharField(verbose_name=_('Password'), max_length=255)
    first_name = models.CharField(verbose_name=_('First Name'), max_length=30, null=True)
    last_name = models.CharField(verbose_name=_('Last Name'), max_length=30, null=True)
    created_at = models.DateField(verbose_name=_('CreatedAt'), auto_now_add=True, db_index=True)
    
    USERNAME_FIELD = 'email'
    objects = UserManager()
    
    def __str__(self):
        return f'{self.first_name} {self.last_name}'

dlearn/authentication/forms.py
from django.utils.translation import gettext_lazy as _
from django import forms

from .errors import ErrorMessages
from .models import CustomUser
from .validators import is_password_valid


def set_default_attrs(**kwargs):
    attrs = {
        'class': 'form-control form-input'
    }
    for k, v in kwargs.items():
        attrs[k] = v
    return attrs


class RegistrationForm(forms.ModelForm):
    
    password = forms.CharField(min_length=6, max_length=30, required=True, widget=forms.PasswordInput(
        attrs=set_default_attrs(placeholder='Пароль', id='register_password')
    ))
    confirm_password = forms.CharField(min_length=6, max_length=30, required=True, widget=forms.PasswordInput(
        attrs=set_default_attrs(placeholder='Повторіть Пароль', id='register_confirm_password')
    ))
    
    class Meta:
        model = CustomUser
        fields = [
            'email',
            'password',
            'confirm_password',
            'first_name',
            'last_name',
        ]
        widgets = {
            'email': forms.EmailInput(attrs=set_default_attrs(placeholder='Емейл')),
            'first_name': forms.TextInput(attrs=set_default_attrs(placeholder='Ім\'я')),
            'last_name': forms.TextInput(attrs=set_default_attrs(placeholder='Прізвище')),
        }
        
    def clean(self):
        """Redefined method clean from ModelForm to add password confimation

        Raises:
            forms.ValidationError: 
                - raise if password and confirm password don't match
                - raise of password doesn't contain at least 1 character and at least 1 number
        """
        cleaned_data = super(RegistrationForm, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')
        
        if not is_password_valid(password):
            self.errors['password'] = ErrorMessages.PASSWORD_VALIDATION_ERROR
            return
        if password != confirm_password:
            self.errors['password'] = ErrorMessages.PASSWORD_NOT_MATCH_ERROR
            return
    
    def save(self, commit=True):
        """Redefined method save from ModelForm

        Args:
            commit (bool, optional): 
            set to True in case to commit changes, set to False to get user object without commiting. Defaults to True.

        Returns:
            CustomUser: user object
        """
        user = super(RegistrationForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password'])
        
        if commit:
            user.save()
        return user


class LoginForm(forms.ModelForm):
    
    password = forms.CharField(max_length=30, widget=forms.PasswordInput(
        attrs=set_default_attrs(placeholder='Пароль')
    ))
    
    class Meta:
        model = CustomUser
        fields = ['email']
        widgets = {
            'email': forms.EmailInput(attrs=set_default_attrs(placeholder='Електронна Адреса'))
        }

dlearn/authentication/api/views.py
from rest_framework.authtoken.views import ObtainAuthToken

from .serializers import AuthTokenSerializer


class ReceiveAuthToken(ObtainAuthToken):
    serializer_class = AuthTokenSerializer

dlearn/authentication/views.py
from django.contrib.auth import login, logout
from django.shortcuts import redirect, render
from django.views import View
from django.core.exceptions import ObjectDoesNotExist

from .errors import ErrorMessages
from .models import CustomUser
from .forms import RegistrationForm, LoginForm


class RegisterView(View):
    """
        RegisterView provides operations for user registration.
        
        Attributes:
        ----------
        param template_name: Describes template name for render
        type template_name: str
        param form: Describes django-form for registration
        type form: RegistrationForm
    """
    template_name = 'authentication/register.html'
    form = RegistrationForm
    
    def get(self, request):
        return render(request, self.template_name, {'form': self.form})

    def post(self, request):
        form = self.form(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/')
        return render(request, self.template_name, {'form': form})
    

class LoginView(View):
    """
        LoginView provides operations for user loging in.
        
        Attributes:
        ----------
        param template_name: Describes template name for render
        type template_name: str
        param form: Describes django-form for logining in
        type form: LoginForm
    """
    template_name = 'homepage/index.html'
    form = LoginForm
    
    def get(self, request):
        login_open = False
        if request.GET.get('login_open') == 'open':
            login_open = True
        
        return render(request, self.template_name, {'login_form': LoginForm, 'open': login_open})
    
    def post(self, request):
        form = self.form(request.POST)
        
        try:
            user = CustomUser.objects.get(email=form.data['email'])
        except ObjectDoesNotExist:
            user = None
        
        if not user or not user.check_password(form.data['password']):
            form.errors['email'] = form.error_class([ErrorMessages.USER_NOT_FOUND_ERROR])
            return render(request, self.template_name, {'login_form': form, 'login_error': True})
        
        login(request, user)
        user.save()

        return redirect('/')


class LogoutView(View):
    """
        LogoutView provides opeartions for user logining out.
    """
    def get(self, request):
        if request.user.is_authenticated:
            request.user.save()
            logout(request)
        return redirect('/')

dlearn/authentication/templates/authentication/login.html
{% load static %}

<div class="container login-form">
    <h3 class="text-center login-form-header">Увійдіть до Акаунту</h3>
    <form action="{% url 'authentication:login' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <img src="{% static 'homepage/open-iconic/svg/envelope-closed.svg' %}" class="form-svg envelope-svg">{{ login_form.email }}
        </div>
        <div class="form-group">
            <img src="{% static 'homepage/open-iconic/svg/lock-locked.svg' %}" class="form-svg">{{ login_form.password }}
            <small class="form-error">{{ login_form.email.errors }}</small>  
        </div>
        <a href="#" class="form-link">Забули пароль?</a>
        <div class="form-group">
            <input type="submit" class="form-btn" value="Увійти">
        </div>
        <div class="text-center form-bottom-text">
            <small>Ще нема акаунту? <a href="{% url 'authentication:register' %}" class="form-link">Створіть зараз</a></small>
        </div>
    </form>
</div>

dlearn/authentication/templates/authentication/register.html
{% extends 'homepage/_base.html' %}
{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static 'authentication/style.css' %}">
{% endblock styles %}

{% block content %}
<div class="container login-form register-form">
    <div class="form-group">
        <form action="{% url 'authentication:register' %}" method="POST">
            {% csrf_token %}
            <div class="form-group text-center">
                <h3 class="login-form-header">Створіть ваш DLearn акаунт</h3>
            </div>
            <div class="form-group row">
                <div class="form-group col-md-6">
                    <img src="{% static 'homepage/open-iconic/svg/person.svg' %}" class="form-svg person-svg">{{ form.first_name }}
                </div>
                <div class="form-group col-md-6">
                    <img src="{% static 'homepage/open-iconic/svg/person.svg' %}" class="form-svg person-svg">{{ form.last_name }}
                </div>
            </div>
            <div class="form-group">
                <img src="{% static 'homepage/open-iconic/svg/envelope-closed.svg' %}" class="form-svg envelope-svg">{{ form.email }}
                {% if form.errors.email %}
                    <small class="form-error">
                        <ul>
                            <li>Користувач з таким емейлом уже існує</li>
                        </ul>
                    </small>
                {% endif %}
            </div>
            <div class="form-group row">
                <div class="form-group col-md-6">
                    <img src="{% static 'homepage/open-iconic/svg/lock-locked.svg' %}" class="form-svg lock-svg">{{ form.password }}
                </div>
                <div class="form-group col-md-6">
                    <img src="{% static 'homepage/open-iconic/svg/lock-locked.svg' %}" class="form-svg lock-svg">{{ form.confirm_password }}
                </div>
                <small class="form-error">{{ form.errors.password }}</small>
            </div>
            <div class="form-group">
                <div class="form-group col-md-6">
                    <label>
                        <input type="checkbox" id="show_password" onclick="showPassword()">
                        Показати пароль
                    </label>
                </div>
            </div>
            <div class="form-group text-center">
                <input class="form-btn" type="submit" value="Створити Акаунт">
            </div>
            <div class="text-center form-bottom-text">
                <small>Вже зареєстровані? <a href="{% url 'authentication:login' %}?login_open=open" class="form-link">Зайдіть в акаунт</a></small>
            </div>
        </form>
    </div>
</div>
{% endblock %}