dlearn/dlearn/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('course/', include('course.urls')),
    path('course/', include('task.urls')),
    path('course/', include('quiz.urls')),
    path('', include('homepage.urls')),
    # path('__debug__/', include('debug_toolbar.urls'))
]

api_urlpatterns = [
    path('auth/', include('authentication.api.urls')),
    path('course/', include('course.api.urls')),
    path('task/', include('task.api.urls')),
    path('quiz/', include('quiz.api.urls')),
]

urlpatterns += [
    path('api/1.0/', include(api_urlpatterns)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dlearn/quiz/urls.py
from django.urls import path

from .views import QuizCreateView, QuizDetailView, UserDetailView


app_name = 'quiz'
urlpatterns = [
    path('<int:course_id>/task/<int:task_id>/create-quiz/', view=QuizCreateView.as_view(), name='create'),
    path('<int:course_id>/task/<int:task_id>/quiz/', view=QuizDetailView.as_view(), name='detail'),
    path('<int:course_id>/task/<int:task_id>/quiz/user-detail/<int:user_id>/', view=UserDetailView.as_view(), name='user_detail')
]

dlearn/task/api/urls.py
from django.urls import path

from .views import TaskAPIView, UserFilesAPIView, OwnerFilesAPIView, TaskListAPIView


app_name='task_api'

urlpatterns = [
    path('', TaskAPIView.as_view(), name='detail'),
    path('list/', TaskListAPIView.as_view(), name='list'),
    path('user-files/', UserFilesAPIView.as_view(), name='user_files'),
    path('owner-files/', OwnerFilesAPIView.as_view(), name='owner_files')
]

dlearn/task/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import (
    TaskCreateView,
    TaskDetailView,
    TaskDeleteView,
    TaskUpdateView,
    DeleteOwnerFileView,
    DeleteUserFileView,
    AddUserFilesView,
    UserFilesListView,
    UserRatingView
)


app_name = 'task'
urlpatterns = [
    path('<int:course_id>/create-task/', login_required(TaskCreateView.as_view()), name='create'),
    path('<int:course_id>/task/<int:task_id>/', login_required(TaskDetailView.as_view()), name='detail'),
    path('<int:course_id>/task/<int:task_id>/delete/', login_required(TaskDeleteView.as_view()), name='delete'),
    path('<int:course_id>/task/<int:task_id>/update/', login_required(TaskUpdateView.as_view()), name='update'),
    path('<int:course_id>/task/<int:task_id>/delete-owner-file/<int:file_id>/', 
         login_required(DeleteOwnerFileView.as_view()),
         name='delete_owner_file'
    ),
    path('<int:course_id>/task/<int:task_id>/delete-user-file/<int:file_id>/',
         login_required(DeleteUserFileView.as_view()),
         name='delete_user_file'
    ),
    path('<int:course_id>/task/<int:task_id>/add-files/', login_required(AddUserFilesView.as_view()), name='add_files'),
    path('<int:course_id>/task/<int:task_id>/user-files/', login_required(UserFilesListView.as_view()), name='user_files'),
    path('<int:course_id>/task/<int:task_id>/user-rating/', login_required(UserRatingView.as_view()), name='user_rating')
]

dlearn/task/models.py
import os
import uuid

from django.db import models
from django.db.models.deletion import CASCADE
from django.utils.translation import gettext_lazy as _

from dlearn.settings import MEDIA_ROOT
from dlearn.storage_backends import PrivateMediaStorage
from course.models import Course
from authentication.models import CustomUser


def user_directory_path(instance, filename):
    return MEDIA_ROOT / f'users/user_{instance.user.id}/task_{instance.task.id}/{uuid.uuid1()}/{filename}'

def owner_directory_path(instance, filename):
    return MEDIA_ROOT / f'owners/owner_{instance.owner.id}/task_{instance.task.id}/{uuid.uuid1()}/{filename}'


class Task(models.Model):
    name = models.CharField(max_length=128, verbose_name=_('Name'))
    course = models.ForeignKey(Course, on_delete=CASCADE, verbose_name=_('Course'))
    max_mark = models.IntegerField(default=0)
    description = models.TextField(null=True, blank=True, verbose_name=_('Description'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('Created At'))
    do_up_to = models.DateTimeField(null=True, blank=True, verbose_name=_('Do Up To'))
    
    class Meta:
        ordering = ['created_at']


class OwnerTaskFile(models.Model):
    owner = models.ForeignKey(CustomUser, on_delete=CASCADE)
    task = models.ForeignKey(Task, on_delete=CASCADE)
    media = models.FileField(storage=PrivateMediaStorage(), null=True, blank=True, verbose_name=_('Media'), max_length=256)
    
    def __str__(self):
        return os.path.basename(self.media.name)


class UserTaskFile(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=CASCADE)
    task = models.ForeignKey(Task, on_delete=CASCADE)
    media = models.FileField(storage=PrivateMediaStorage(), null=True, blank=True, verbose_name=_('Media'), max_length=256)
    done_at = models.DateTimeField(auto_now_add=True)
    too_late = models.BooleanField(default=False)
    
    def __str__(self):
        return os.path.basename(self.media.name)


class UserTask(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=CASCADE, verbose_name=_('User'))
    task = models.ForeignKey(Task, on_delete=CASCADE, verbose_name=_('Task'))
    is_examined = models.BooleanField(default=False)
    mark = models.PositiveIntegerField(default=0, null=True, blank=True, verbose_name=_('Mark'))
    done_at = models.DateTimeField(auto_now_add=True, null=True, blank=True, verbose_name=_('Done At'))

dlearn/task/forms.py
from django import forms
from django.forms.utils import ErrorList
from django.utils import timezone
from django.forms import widgets

from datetime import datetime

from .models import Task


class TaskForm(forms.ModelForm):
    
    file = forms.FileField(
        required=False, 
        widget=forms.ClearableFileInput(attrs={
            'multiple': False, 
            'class': 'form-control', 
            'id': 'taskFiles'
        })
    )
    do_up_to = forms.DateTimeField(
        required=False,
        input_formats=['%d/%m/%Y %H:%M'],
        widget=forms.DateTimeInput(attrs={
            'type': 'datetime-local',
            'class': 'form-control',
            'id': 'taskDateTime'
        })
    )
    
    class Meta:
        model = Task
        exclude = ('course', 'has_quiz')
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control', 
                'placeholder': 'Назва завдання',
                'id': 'taskName'
            }),
            'description': forms.Textarea(attrs={
                'class': 'form-control', 
                'placeholder': 'Опис завдання',
                'id': 'taskDescription',
                'required': True
            }),
            'max_mark': forms.NumberInput(attrs={
                'class': 'form-control',
                'placeholder': 'Максимальний бал',
                'min': '0',
                'id': 'taskMaxMark'
            })
        }
        
    def clean(self):
        cleaned_data = super(TaskForm, self).clean()
        
        if cleaned_data['do_up_to'] and timezone.now() > cleaned_data['do_up_to']:
            errors = self._errors.setdefault('do_up_to', ErrorList())
            errors.append('Некоретні дата та/або час')
            raise forms.ValidationError('Некоретні дата та/або час')

dlearn/task/api/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from rest_framework.parsers import FileUploadParser, JSONParser
from rest_framework.status import HTTP_400_BAD_REQUEST, HTTP_404_NOT_FOUND, HTTP_403_FORBIDDEN, HTTP_204_NO_CONTENT, HTTP_201_CREATED

from course.models import Course
from .serializers import TaskSerializer, UserTaskSerializer, UserTaskFileSerializer, OwnerTaskFileSerializer
from ..models import Task, OwnerTaskFile, UserTask, UserTaskFile


class TaskAPIView(APIView):
    permission_classes = (IsAuthenticated,)
    serializer_class = TaskSerializer

    def get(self, request):
        task_id = request.data.get('id')
        
        if not task_id:
            return Response('id is required', status=HTTP_400_BAD_REQUEST)

        try:
            task_id = int(task_id)
        except ValueError:
            return Response('id must be a number', status=HTTP_400_BAD_REQUEST)

        if not Task.objects.filter(id=task_id).exists():
            return Response(status=HTTP_404_NOT_FOUND)
        
        task = Task.objects.get(id=task_id)
        
        serializer = self.serializer_class(instance=task)
        return Response(serializer.data)

    def post(self, request):
        course_id = request.data.get('course_id')
        
        if not course_id:
            return Response('id is required', status=HTTP_400_BAD_REQUEST)
        
        try:
            course_id = int(course_id)
        except ValueError:
            return Response('id must be a number', status=HTTP_400_BAD_REQUEST)
        
        if not Course.objects.filter(id=course_id).exists():
            return Response(status=HTTP_404_NOT_FOUND)
        
        if Course.objects.get(id=course_id).owner != request.user:
            return Response(status=HTTP_403_FORBIDDEN)
        
        data = request.data.copy()
        data.update({'course': course_id})
        serializer = self.serializer_class(data=data)

        if serializer.is_valid(raise_exception=True):
            task = serializer.save()
            return Response(self.serializer_class(instance=task).data)

        return Response(status=HTTP_400_BAD_REQUEST)
    
    def delete(self, request):
        task_id = request.data.get('task_id')
        
        if not task_id:
            return Response('id is required', status=HTTP_400_BAD_REQUEST)

        try:
            task_id = int(task_id)
        except ValueError:
            return Response('id must be a number', status=HTTP_400_BAD_REQUEST)

        if not Task.objects.filter(id=task_id).exists():
            return Response(status=HTTP_404_NOT_FOUND)
        
        task = Task.objects.get(id=task_id)

        if task.course.owner != request.user:
            return Response(status=HTTP_403_FORBIDDEN)

        serializer = self.serializer_class(instance=task)
        task = task.delete()
        
        return Response(serializer.data, status=HTTP_204_NO_CONTENT)


class TaskListAPIView(APIView):
    permission_classes = (IsAuthenticated,)
    serializer_class = TaskSerializer
    
    def get(self, request):
        course_id = request.data.get('course_id')
        
        if not course_id:
            return Response(status=HTTP_400_BAD_REQUEST)
        
        try:
            course_id = int(course_id)
        except ValueError:
            return Response(status=HTTP_400_BAD_REQUEST)
        
        if not Course.objects.filter(id=course_id).exists():
            return Response(status=HTTP_404_NOT_FOUND)
        
        course = Course.objects.get(id=course_id)
        serializer = self.serializer_class(instance=course.task_set.all(), many=True)
        
        return Response(serializer.data)


class OwnerFilesAPIView(APIView):
    parser_classes = (FileUploadParser, JSONParser)
    permission_classes = (IsAuthenticated,)
    serializer_class = OwnerTaskFileSerializer
    
    def get(self, request):
        task_id = request.data.get('task_id')
        
        if not task_id:
            return Response('id is required', status=HTTP_400_BAD_REQUEST)

        try:
            task_id = int(task_id)
        except ValueError:
            return Response('id must be a number', status=HTTP_400_BAD_REQUEST)

        if not Task.objects.filter(id=task_id).exists():
            return Response(status=HTTP_404_NOT_FOUND)
        
        task = Task.objects.get(id=task_id)
        task_files = OwnerTaskFile.objects.filter(task=task)
        serializer = self.serializer_class(instance=task_files, many=True)
        
        return Response(serializer.data)
    
    def post(self, request):
        files = request.FILES
        task_id = request.data.get('task_id')
        print(task_id)
        if not task_id:
            return Response('id is required', status=HTTP_400_BAD_REQUEST)

        try:
            task_id = int(task_id)
        except ValueError:
            return Response('id must be a number', status=HTTP_400_BAD_REQUEST)

        if not Task.objects.filter(id=task_id).exists():
            return Response(status=HTTP_404_NOT_FOUND)

        task = Task.objects.get(id=task_id)
        
        if task.course.owner != request.user:
            return Response(status=HTTP_403_FORBIDDEN)

        for file in files:
            data = {
                'owner': request.user.id,
                'media': file,
                'task': task.id
            }
            serializer = self.serializer_class(data=data)

            if not serializer.is_valid(raise_exception=True):
                return Response(status=HTTP_400_BAD_REQUEST)
            
            serializer.save()

        return Response(status=HTTP_201_CREATED)


class UserFilesAPIView(APIView):
    permission_classes = (IsAuthenticated,)
    serializer_class = UserTaskFileSerializer
    
    def get(self, request):
        task_id = request.data.get('task_id')
        
        if not task_id:
            return Response('id is required', status=HTTP_400_BAD_REQUEST)

        try:
            task_id = int(task_id)
        except ValueError:
            return Response('id must be a number', status=HTTP_400_BAD_REQUEST)

        if not Task.objects.filter(id=task_id).exists():
            return Response(status=HTTP_404_NOT_FOUND)

        task = Task.objects.get(id=task_id)
        user_files = UserTaskFile.objects.filter(task=task, user=request.user)
        serializer = self.serializer_class(instance=user_files, many=True)
        
        return Response(serializer.data)
    
    def post(self, request):
        files = request.FILES.getlist('file')
        task_id = request.data.get('task_id')
        
        if not task_id:
            return Response(status=HTTP_400_BAD_REQUEST)

        try:
            task_id = int(task_id)
        except ValueError:
            return Response(status=HTTP_400_BAD_REQUEST)

        if not Task.objects.filter(id=task_id).exists():
            return Response(status=HTTP_404_NOT_FOUND)

        task = Task.objects.get(id=task_id)
        

        for file in files:
            data = {
                'user': request.user,
                'media': file,
                'task': task
            }
            serializer = self.serializer_class(data=data)
            serializer.save()

        return Response(status=HTTP_201_CREATED)

dlearn/task/templates/task/create.html
{% extends 'homepage/_base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'task/style.css' %}">
{% endblock styles %}

{% block content %}
<div class="container task-create-container">
    <div class="row">
        <h2 class="task-form-header">Створення завдання для курсу <b>"{{ course.name }}"</b></h2>
    </div>
    <form action="{% url 'task:create' course.id %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="taskName">Назва завдання:</label>
            {{ task_form.name }}
        </div>
        <div class="form-group row">
            <div class="col">
                <label for="taskDateTime">Термін виконання:</label>
                {{ task_form.do_up_to }}
                <small class="form-error">{{ task_form.do_up_to.errors.0 }}</small>
            </div>
            <div class="col">
                <label for="taskMaxMark">Максимальний бал:</label>
                {{ task_form.max_mark }}
            </div>
        </div>
        <div class="form-group">
            {{ task_form.description }}
        </div>
        <div class="form-group">
            <label for="taskFiles">Завантажте файли для завдання:</label>
            {{ task_form.file }}
        </div>
        <div class="form-group text-center">
            <input class="task-create-button" type="submit" value="Створити завдання">
        </div>
    </form>
</div>

{% endblock %}

dlearn/task/templates/task/detail.html
{% extends 'homepage/_base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'task/style.css' %}">
{% endblock styles %}

{% block content %}
<div class="task-container">

    <div class="row task-head-row">
        <div class="col">
            <h2 class="col task-header">{{ task.name }}</h2>
            <small class="task-time">
                {% if not is_owner and user_files.0.too_late %}
                    <span style="color: red">
                        <b>Здано з запізенням</b>
                    </span>
                {% elif not is_onwer and too_late %}
                    <span style="color: red">
                        <b>Не здано</b>
                    </span>
                {% elif not too_late and user_files %}
                    <span>
                        <b>Здано</b>
                    </span>
                {% else %}
                    <b>Виконати до: <span>{{ task.do_up_to }} </span></b>
                {% endif %}
            </small>
        </div>

        <small class="col mark-container">
            {% if is_examined and not task.max_mark %}
                Оцінка: {{ mark }}
            {% elif is_examined and task.max_mark %}
                Оцінка: {{ mark }} / {{ task.max_mark }}
            {% elif task.max_mark != 0 and not is_examined %}
                Максимальний бал: {{ task.max_mark }}
            {% else %}
                Не оцінено
            {% endif %}
        </small>
    </div>

    <div class="row description-header">
        <h5 class="col">Опис завдання:</h5>

        {% if owner_files %}
            <h5 class="col-md-3 files-header">Файли завдання:</h5>
        {% endif %}

        {% if not is_owner %}
            <h5 class="col-md-3 user-files-header">Ваші файли:</h5>
        {% endif %}
    </div>
    <div class="row task-central-row">
        <div class="col task-description">
            <p>{{ task.description }}</p>
        </div>

        {% if owner_files %}

            <div class="col-md-3 owner-files-container">
                {% for file in owner_files %}
                    <div class="row task-file">
                        <div class="col">
                            {{ file }}
                        </div>
                        {% if not is_owner %}
                            <div class="col-md-2">
                        {% else %}
                            <div class="col-md-1">
                        {% endif %}
                            <a class="file-load-link" href="{{ file.media.url }}" download>
                                <img src="{% static 'homepage/open-iconic/svg/data-transfer-download.svg' %}" class="download-svg">
                            </a>
                        </div>

                        {% if is_owner %}
                            <div class="col-md-2">
                                <form action="{% url 'task:delete_owner_file' course_id task.id file.id %}" method="POST">
                                    {% csrf_token %}
                                    <button type="submit" class="file-delete-button">
                                        <img src="{% static 'homepage/open-iconic/svg/circle-x.svg' %}" class="delete-file-svg">
                                    </button>
                                </form>
                            </div>
                        {% endif %}

                    </div>
                {% endfor %}
            </div>
        {% endif %}

        {% if not is_owner %}

            <!-- user files -->
            <div class="col-md-3" style="padding-left: 0;">
                <div class="col owner-files-container user-files-container">
                    {% for file in user_files %}
                        <div class="row task-file">
                            <div class="col">
                                {{ file }}
                            </div>
                            <div class="col-md-1">
                                <a class="file-load-link" href="{{ file.media.url }}" download>
                                    <img src="{% static 'homepage/open-iconic/svg/data-transfer-download.svg' %}" class="download-svg">
                                </a>
                            </div>
                            <div class="col-md-2">
                                <form action="{% url 'task:delete_user_file' course_id task.id file.id %}" method="POST">
                                    {% csrf_token %}
                                    <!-- <input class="file-delete-button" type="submit" value="&#10060;" title="Видалити файл"> -->
                                    <button type="submit" class="file-delete-button">
                                        <img src="{% static 'homepage/open-iconic/svg/circle-x.svg' %}" class="delete-file-svg">
                                    </button>
                                </form>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <div class="row user-files-input">
                    <form action="{% url 'task:add_files' course_id task.id %}" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-9">
                                <input class="form-control" type="file" name="file" multiple>
                            </div>
                            <div class="col load-files-container">
                                <input class="load-files-button" type="submit" value="Прикріпити">
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        {% endif %}
    </div>

    <div class="row buttons-container">
        {% if is_owner %}
            <div class="col">
                <a href="{% url 'task:update' task.course.id task.id %}">
                    <button class="task-button">Редагувати</button>
                </a>
                <a href="{% url 'task:user_files' task.course.id task.id %}">
                    <button class="task-button">Файли користувачів</button>
                </a>
                <a href="{% url 'task:user_rating' task.course.id task.id %}">
                    <button class="task-button">Рейтинг</button>
                </a>

                {% if not quiz %}
                    <a href="{% url 'quiz:create' task.course.id task.id %}">
                        <button class="task-button">Додати тестове завдання</button>
                    </a>
                {% endif %}
            </div>

            {% if quiz %}
                <div class="col-md-3">
                    <div class="row quiz-buttons-row">
                        <div class="col btn-quiz">
                            <a href="{% url 'quiz:detail' task.course.id task.id %}">
                                <button class="quiz-button">Тестове завдання</button>
                            </a>
                        </div>
        
                        <div class="col">
                            <form action="{% url 'task:detail' task.course.id task.id %}" method="POST">
                            {% csrf_token %}
                                <input class="delete-quiz-button" type="submit" value="Видалити тестове завдання">
                            </form>
                        </div>
                    </div>
                </div>
            {% endif %}
        {% elif quiz %}
            <div class="col quiz-div">
                <a href="{% url 'quiz:detail' task.course.id task.id %}">
                    <button class="quiz-button" style="width: 10%">Тестове завдання</button>
                </a>
            </div>
        {% endif %}

    </div>
    </div>
</div>

<!-- <div>
    <div class="col-md-12 upper-row">
        <div class="row">
            <div class="col-md-6"><h1>{{ task.name }}</h1></div>
            {% if is_eximined %}
                <div class="col-md-6"><span class="time-line">{{ mark }} / {{ task.max_mark }}</span></div>
            {% elif task.max_mark == 0 %}
                
            {% else %}
                <div class="col-md-6"><span class="time-line">не оцінено</span></div>
            {% endif %}
        </div>
    </div>
    <div class="row">
        {% if owner_files %}
            <div class="col-md-6">
        {% else %}
            <div class="col-md-12">
        {% endif %}
            <h3 class="headers">Опис:</h3>
            <div id="description-div">
                {{ task.description }}
            </div>
        </div>
        {% if owner_files %}
            <div class="col-md-6 file-container">
                <h3>Прикріплені файли:</h3>
                <div id="file-div">
                    {% for file in owner_files %}
                        <div class="row">
                            <div class="col-md-10 file">
                                <a href="{{ file.media.url }}" download>{{ file }}</a>
                            </div>
                            <div>
                                {% if is_owner %}
                                    <form action="{% url 'task:delete_owner_file' course_id task.id file.id %}" method="POST">
                                        {% csrf_token %}
                                        <input class="btn btn-danger" type="submit" value="Видалити">
                                    </form>
                                {% endif %}
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}
    </div>
</div>

{% if is_owner %}
    <div class="row">
        <div class="col-md-6">

            {% if quiz %}
            <div class="row">
                <div class="col-md-2 btn-quiz">
                    <a href="{% url 'quiz:detail' task.course.id task.id %}">
                        <button class="btn btn-success btn-quiz">Тестове завдання</button>
                    </a>
                </div>

                <div class="col-md-2 btn-quiz-delete">
                    <form action="{% url 'task:detail' task.course.id task.id %}" method="POST">
                    {% csrf_token %}
                        <input class="btn btn-danger" type="submit" value="Видалити тестове завдання">
                    </form>
                </div>
            </div>
        </div>
        {% endif %}
        
        
        <div class="col">
            <a href="{% url 'task:update' task.course.id task.id %}">
                <button class="btn btn-info btn-task">Редагувати</button>
            </a>
            <a href="{% url 'task:user_files' task.course.id task.id %}">
                <button class="btn btn-info btn-task">Файли користувачів</button>
            </a>
            <a href="{% url 'task:user_rating' task.course.id task.id %}">
                <button class="btn btn-info btn-task">Рейтинг</button>
            </a>
            {% if not quiz %}
                <a href="{% url 'quiz:create' task.course.id task.id %}">
                    <button class="btn btn-info btn-task">Додати тестове завдання</button>
                </a>
            {% endif %}
        </div>
    </div>
{% endif %}

{% if not is_owner %}
    <div class="row">
        <div class="col-md-6">
            <h3 class="headers">Завантажте ваші файли:</h3>
            <div class="col user-file-div">
                <form action="{% url 'task:add_files' course_id task.id %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-10">
                            <input class="form-control file-input" type="file" name="file" multiple>
                        </div>
                        <div class="col-md-2">
                            <input class="btn btn-info btn-user-files" type="submit" value="Прикріпити">
                        </div>
                    </div>
                </form>
                {% for file in user_files %}
                <div class="row">
                    <div class="col-md-10 file user-file">
                        <a href="{{ file.media.url }}" download>{{ file }}</a>
                    </div>
                    <form action="{% url 'task:delete_user_file' course_id task.id file.id %}" method="POST">
                        {% csrf_token %}
                        <input class="btn btn-danger file-delete-btn" type="submit" value="Видалити">
                    </form>
                </div>
                {% endfor %}
            </div>
        </div>
        {% if quiz %}
            <div class="col text-center quiz-div">
                <a href="{% url 'quiz:detail' task.course.id task.id %}">
                    <button class="btn btn-success btn-quiz-user">Тестове завдання</button>
                </a>
            </div>
        {% endif %}
    </div>
{% endif %} -->

{% endblock content %}

dlearn/task/templates/task/users-rating.html
{% extends 'homepage/_base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'task/style.css' %}">
{% endblock styles %}

{% block content %}
<div class="container rating-container">
    <div class="row header-container">
        <h3 class="rating-header">Результати завдання</h3>
    </div>
    <table>
        <tr>
            <th></th>
            <th>Студент</th>
            <th>Завдання</th>
            <th>Тести</th>
            <th>Загальний результат</th>
        </tr>

        {% for user, marks in users_marks.items %}
            <tr>
                <td class="table-counter">{{ forloop.counter }}</td>
                <td class="table-username">{{ user.first_name }} {{ user.last_name }}</td>

                {% for mark in marks %}
                    <td class="mark">{{ mark }}</td>
                {% endfor %}

            </tr>
        {% endfor %}

    </table>
</div>
{% endblock content %}