dlearn/dlearn/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('course/', include('course.urls')),
    path('course/', include('task.urls')),
    path('course/', include('quiz.urls')),
    path('', include('homepage.urls')),
    # path('__debug__/', include('debug_toolbar.urls'))
]

api_urlpatterns = [
    path('auth/', include('authentication.api.urls')),
    path('course/', include('course.api.urls')),
    path('task/', include('task.api.urls')),
    path('quiz/', include('quiz.api.urls')),
]

urlpatterns += [
    path('api/1.0/', include(api_urlpatterns)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dlearn/quiz/api/urls.py
from django.urls import path

from .views import (
    QuizAPIView, 
    QuestionAPIVIew, 
    OptionAPiView, 
    StartQuizAPIView, 
    QuestionSelectOptionsAPIView,
    QuestionAddTextAnswer,
    QuestionSetMark,
    CountMarkForQuiz,
    UserResultAPIView,
    ResultDetailAPIView
)


app_name = 'quiz_api'

urlpatterns = [
    path('', QuizAPIView.as_view(), name='quiz'),
    path('user-result/', UserResultAPIView.as_view(), name='user_result'),
    path('start/', StartQuizAPIView.as_view(), name='start'),
    path('question/', QuestionAPIVIew.as_view(), name='question'),
    path('question/option/', OptionAPiView.as_view(), name='option'),
    path('question/select-options/', QuestionSelectOptionsAPIView.as_view(), name='select_options'),
    path('question/add-text-answer/', QuestionAddTextAnswer.as_view(), name='add_text_answer'),
    path('question/set-mark/', QuestionSetMark.as_view(), name='set_mark'),
    path('count-mark/', CountMarkForQuiz.as_view(), name='count_mark'),
    path('all-results/', ResultDetailAPIView.as_view(), name='result_detail')
]

dlearn/quiz/urls.py
from django.urls import path

from .views import QuizCreateView, QuizDetailView, UserDetailView


app_name = 'quiz'
urlpatterns = [
    path('<int:course_id>/task/<int:task_id>/create-quiz/', view=QuizCreateView.as_view(), name='create'),
    path('<int:course_id>/task/<int:task_id>/quiz/', view=QuizDetailView.as_view(), name='detail'),
    path('<int:course_id>/task/<int:task_id>/quiz/user-detail/<int:user_id>/', view=UserDetailView.as_view(), name='user_detail')
]

dlearn/quiz/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.utils.translation import gettext_lazy as _

from task.models import Task
from authentication.models import CustomUser


class Quiz(models.Model):
    task = models.ForeignKey(Task, on_delete=CASCADE)
    description = models.TextField(null=True)
    
    def get_questions(self):
        return self.question_set.all()


class UserResult(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=CASCADE)
    quiz = models.ForeignKey(Quiz, on_delete=CASCADE)
    mark = models.IntegerField(default=0)


class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=CASCADE)
    question = models.CharField(max_length=550)
    price = models.FloatField(default=0)
    text_answer = models.BooleanField(default=False)
    
    def get_options(self):
        return self.option_set.all()


class Option(models.Model):
    question = models.ForeignKey(Question, on_delete=CASCADE)
    option = models.CharField(max_length=255)
    is_right = models.BooleanField(default=False)


class ResultDetail(models.Model):
    user_result = models.ForeignKey(UserResult, on_delete=CASCADE)
    question = models.ForeignKey(Question, on_delete=CASCADE)
    option = models.ForeignKey(Option, on_delete=CASCADE, null=True, blank=True)
    mark = models.IntegerField(default=0)
    is_right = models.BooleanField(null=True, blank=True)
    text_answer = models.TextField(null=True, blank=True)

dlearn/quiz/forms.py
from django import forms

from .models import Quiz


class QuizForm(forms.ModelForm):
    
    class Meta:
        model = Quiz
        fields = '__all__'

dlearn/quiz/api/views.py
from django.shortcuts import get_object_or_404, get_list_or_404

from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated
from rest_framework.status import HTTP_201_CREATED, HTTP_400_BAD_REQUEST, HTTP_200_OK, HTTP_403_FORBIDDEN

from .serializers import QuizSerializer, QuestionSerializer, OptionSerializer, UserResultSerializer, ResultDetailSerializer
from ..models import Quiz, Option, Question, UserResult, ResultDetail


def count_mark_for_question(question, selected_options):
    right_options, false_options = 0, 0
    right_selected_options, false_selected_options = 0, 0
    
    for option in question.get_options():
        if option.is_right:
            right_options += 1
        else:
            false_options += 1
    
    for option in selected_options:
        if option.is_right:
            right_selected_options += 1
        else:
            false_selected_options += 1
    
    right_percent = right_selected_options / right_options
    false_percent = false_selected_options / false_options
    
    mark = round(question.price * (right_percent - false_percent))
    return mark if mark > 0 else 0


class QuizAPIView(APIView):
    permission_classes = (IsAuthenticated,)
    serializer_class = QuizSerializer

    def get(self, request):
        quiz = get_object_or_404(Quiz, id=request.data['quiz_id'])
        serializer = self.serializer_class(instance=quiz)
        return Response(serializer.data)

    def post(self, request):
        serializer = self.serializer_class(data=request.data)
        
        if serializer.is_valid(raise_exception=True):
            quiz = serializer.save()
            return Response(self.serializer_class(instance=quiz).data, status=HTTP_201_CREATED)
        return Response(status=HTTP_400_BAD_REQUEST)

    def delete(self, request):
        pass


class QuestionAPIVIew(APIView):
    permission_classes = (IsAuthenticated,)
    serializer_class = QuestionSerializer
    
    def get(self, request):
        question = get_object_or_404(Question, id=request.data['id'])
        serializer = self.serializer_class(instance=question)
        return Response(serializer.data)

    def post(self, request):
        serializer = self.serializer_class(data=request.data)

        if serializer.is_valid(raise_exception=True):
            question = serializer.save()
            return Response(self.serializer_class(instance=question).data, status=HTTP_201_CREATED)
        return Response(status=HTTP_400_BAD_REQUEST)


class OptionAPiView(APIView):
    permission_classes = (IsAuthenticated,)
    serializer_class = OptionSerializer
    
    def get(self, request):
        option = get_object_or_404(Option, id=request.data['id'])
        serializer = self.serializer_class(instance=option)
        return Response(serializer.data)
    
    def post(self, request):
        serializer = self.serializer_class(data=request.data)
        
        if serializer.is_valid(raise_exception=True):
            option = serializer.save()
            return Response(self.serializer_class(instance=option).data, status=HTTP_201_CREATED)

        return Response(status=HTTP_400_BAD_REQUEST)


class StartQuizAPIView(APIView):
    permission_classes = (IsAuthenticated,)
    serializer_class = UserResultSerializer
    
    def post(self, request):
        data = request.data.copy()
        data.update({'user': request.user.id})
        serializer = self.serializer_class(data=data)

        if UserResult.objects.filter(user=data['user'], quiz=data['quiz']).exists():
            return Response('This user is already started this quiz.', status=HTTP_403_FORBIDDEN)
        
        if serializer.is_valid(raise_exception=True):
            user_result = serializer.save()
            return Response(self.serializer_class(instance=user_result).data, status=HTTP_201_CREATED)


class UserResultAPIView(APIView):
    permission_classes = (IsAuthenticated,)
    serializer_class = UserResultSerializer
    
    def get(self, request):
        user_result = get_object_or_404(UserResult, user=request.data.get('user'), quiz=request.data.get('quiz'))
        serializer = self.serializer_class(instance=user_result)
        return Response(serializer.data)


class QuestionSelectOptionsAPIView(APIView):
    permission_classes = (IsAuthenticated,)
    serializer_class = ResultDetailSerializer
    
    def post(self, request):
        user_result = get_object_or_404(UserResult, id=request.data.get('user_result'))
        question = get_object_or_404(Question, id=request.data.get('question'))
        options = []
        
        for option in request.data.get('options'):
            options.append(get_object_or_404(Option, id=option))
            
            if options[-1] not in question.get_options():
                return Response(f'There is no such option for Question[{question.id}]', status=HTTP_400_BAD_REQUEST)
        
        for option in options:
            data = {
                'user_result': user_result.id,
                'question': question.id,
                'option': option.id,
                'mark': count_mark_for_question(question, options),
                'is_right': option.is_right
            }
            serializer = self.serializer_class(data=data)
            
            if not serializer.is_valid(raise_exception=True):
                serializer.save()
        
        return Response(status=HTTP_201_CREATED)


class QuestionAddTextAnswer(APIView):
    permission_classes = (IsAuthenticated,)
    serializer_class = ResultDetailSerializer
    
    def post(self, request):
        user_result = get_object_or_404(UserResult, id=request.data.get('user_result'))
        question = get_object_or_404(Question, id=request.data.get('question'))
        text_answer = request.data.get('text_answer')
        
        if not question.text_answer:
            return Response('Question[{question.id}] can not has text answer.', status=HTTP_400_BAD_REQUEST)
        if not text_answer:
            return Response('Text answer can not be Null.', status=HTTP_400_BAD_REQUEST)
        
        data = {
            'user_result': user_result.id,
            'question': question.id,
            'text_answer': text_answer
        }
        
        serializer = self.serializer_class(data=data)
        
        if not serializer.is_valid(raise_exception=True):
            return Response(status=HTTP_400_BAD_REQUEST)
            
        serializer.save()
        return Response(status=HTTP_201_CREATED)
    

class QuestionSetMark(APIView):
    permission_classes = (IsAuthenticated,)
    serializer_class = ResultDetailSerializer
    
    def put(self, request):
        user_result = get_object_or_404(UserResult, id=request.data.get('user_result'))
        result_detail = get_object_or_404(ResultDetail, user_result=user_result, question=request.data.get('question'))
        mark = request.data.get('mark')
        
        if result_detail.text_answer is None:
            return Response('You can not set a mark for user they did not give an answer.', status=HTTP_400_BAD_REQUEST)
        
        try:
            mark = int(mark)
        except ValueError:
            return Response('Mark must be an integer.', status=HTTP_400_BAD_REQUEST)

        if mark < 0 or mark > result_detail.question.price:
            return Response(f'Mark can not be negative or higher than question max mark ({result_detail.question.price})', status=HTTP_400_BAD_REQUEST)
        
        result_detail.mark = mark
        result_detail.save()
        return Response(status=HTTP_200_OK)


class CountMarkForQuiz(APIView):
    permission_classes = (IsAuthenticated,)
    serializer_class = UserResultSerializer
    
    def post(self, request):
        user_result = get_object_or_404(UserResult, id=request.data.get('user_result'))
        result_detail = ResultDetail.objects.filter(user_result=user_result)
        
        unique_questions = result_detail.order_by().values('question').distinct()
        total_mark = 0

        for record in unique_questions:
            result = ResultDetail.objects.filter(question=record.get('question'))[0]
            total_mark += result.mark
        
        user_result.mark = total_mark
        user_result.save()
        
        serializer = self.serializer_class(instance=user_result)

        return Response(serializer.data)


class ResultDetailAPIView(APIView):
    permission_classes = (IsAuthenticated,)
    serializer_class = ResultDetailSerializer
    
    def get(self, request):
        user_result = request.data.get('user_result')
        results = get_list_or_404(ResultDetail, user_result=user_result)
        
        serializer = self.serializer_class(instance=results, many=True)
        
        return Response(serializer.data)

dlearn/quiz/templates/quiz/create.html
{% extends 'homepage/_base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'quiz/styles.css' %}">
{% endblock styles %}

{% block content %}
<div class="container quiz-create-container">
    <h2 class="quiz-header">Тестове завдання</h2>
    <form action="{% url 'quiz:create' task.course.id task.id %}" onsubmit="return optionsValidation()" method="POST">
        {% csrf_token %}
        <ol id="questionsList">
            <li>
                <div class="row quiz-row">
                    <div class="col">
                        <label for="question_1">Питання:</label>
                        <input class="form-control" type="text" name="question_1" placeholder="Питання" required>
                    </div>
                    <div class="col-md-2 mark-container">
                        <label for="price_1">Оцінка:</label>
                        <input class="form-control" type="number" name="price_1" placeholder="Бали" required>
                    </div>
                    <div class="col-md-2">
                        <input class="quiz-button" type="button" id="addOptionId" name="optionForQuestion_1" value="Додати варіант" onclick="addOption(1);">
                    </div>
                    <div class="col-md-2 description-check-container">
                        <label class="form-check-label">
                            <input class="form-check-input" type="checkbox" id="textOnly_1" name="textOnlyFor_1" onchange="eraseOptions('questionOptions_1')">
                            Описове завдання
                        </label>
                    </div>
                </div>
                <div class="row">
                    <ul id="questionOptions_1"></ul>
                </div>
            </li>
        </ol>
        <div class="bottom-div">
            <input class="quiz-button add-question-btn" type="button" id="addQuestionId" value="Нове питання" onclick="addQuestion();">
        </div>
        <div class="row create-quiz-btn-row">
            <input class="quiz-create-btn" type="submit" value="Створити тестове завдання">
        </div>
    </form>
</div>  
<script src="{% static 'homepage/js/scripts.js' %}"></script>
{% endblock content %}

dlearn/quiz/templates/quiz/detail.html
{% extends 'homepage/_base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'quiz/styles.css' %}">
{% endblock styles %}

{% block content %}

{% if is_owner %}

<div class="container owner-detail-container">
    <h4 class="quiz-header">Тестове завдання {{ quiz.task.name }}</h4>
    <table>
        <tr>
            <th>Студент</th>
            <th>Результат</th>
            <th></th>
        </tr>

        {% for user_result in users_results %}
        <tr>
            <td class="td-username">{{ user_result.user.first_name }} {{ user_result.user.last_name }}</td>
            <td>{{ user_result.mark }}/{{ max_mark }}</td>
            <td>
                <a href="{% url 'quiz:user_detail' course_id task_id user_result.user.id %}" class="user-detail-link">Переглянути</a>
            </td>
        </tr>
        {% endfor %}

        {% for user in users_not_done %}
        <tr>
            <td>{{ user.first_name }} {{ user.last_name }}</td>
            <td>-</td>
            <td>-</td>
        </tr>
        {% endfor %}

    </table>
</div>

{% elif not is_ready %}

<div class="get-ready-container">
    <h4 class="quiz-header">Тестове завдання {{ quiz.task.name }}</h4>
    <p>
        Кількість запитань: <b>{{ questions|length }}</b><br>
        Максимальний бал: <b>{{ max_mark }}</b>
    </p>
    <form action="{% url 'quiz:detail' course_id task_id %}">
        <input type="submit" value="Почати" name="ready">
    </form>
</div>
{% else %}
<div class="container quiz-detail-container">
    <h3 class="quiz-header">Тестове завдання {{ quiz.task.name }}</h3>
    <form action="{% url 'quiz:detail' course_id task_id %}" method="POST">
        {% csrf_token %}
        <div class="questions-container">
        {% for question in questions %}
            <h6 class="question-text">{{ forloop.counter }}. {{ question.question }}</h6>

            {% if not question.text_answer %}

            <ol type="a" class="options-list">

                {% for option in options %}
                    {% if option.question.id == question.id %}
                            <div class="options-container">
                                <input type="checkbox" name="option_{{ option.id }}">
                                <li>{{ option.option }}</li><br>
                            </div>
                    {% endif %}
                {% endfor %}

            </ol>

            {% else %}
            <textarea class="question-textarea" name="describe_{{ question.id }}" id="describe_{{ question.id }}" cols="30" rows="6" placeholder="Ваша відповідь"></textarea>
            {% endif %}

            <br>
        {% endfor %}
        </div>
        <div class="send-button-container">
            <input class="quiz-send-button quiz-button" type="submit" value="Відправити">
        </div>
    </form>
</div>
{% endif %}
{% endblock content %}

dlearn/quiz/templates/quiz/user-detail.html
{% extends 'homepage/_base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'quiz/styles.css' %}">
{% endblock styles %}

{% block content %}

<div class="container user-result-container">
    <h4 class="quiz-header quiz-detail-header">
        Тестове завдання {{ quiz.task.name }}
        <div>
            <small>
                Виконав: <span>{{ quiz_user.first_name }} {{ quiz_user.last_name }}</span>
            </small>
            <small>
                <small> Оцінка: <span>{{ final_mark }}</span></small>
            </small>
        </div>
    </h4>
{% if is_owner %}
    <form action="{% url 'quiz:user_detail' course_id task_id quiz_user.id %}" method="POST">
    {% csrf_token %}
{% endif %}

    {% for q in questions %}
    <div class="questions-container">
        <p>{{ forloop.counter }}. {{ q.question }}</p>
        <ol class="options-list">
            {% for option in options %}
                {% if option.question == q %}
                <div class="user-options-container">
                    <input type="checkbox" id="checkbox_{{ option.id }}" disabled>
                    <li>
                        <span id="option_{{ option.id }}">{{ option.option }}</span>
                    {% for result in result_details %}
                        {% if result.option == option %}
                            <input type="hidden" name="userAnswer" value="{{ result.option.is_right }}, {{ option.id }}">
                        {% endif %}
                    {% endfor %}
                    </li>
                </div>
                {% endif %}
            {% endfor %}
        </ol>

        {% for result in result_details %}
            {% if result.question == q and result.text_answer %}
                <textarea class="question-textarea" cols="30" rows="5" disabled>
                    {{ result.text_answer }}
                </textarea>
                {% if result.mark == 0 and is_owner %}
                    <label for="descriptionTask_{{ q.id }}">Оцініть завдання:</label><br>
                    <input type="number" class="text-answer-mark" min="0" max="{{ q.price }}" name="descriptionTask_{{ q.id }}" placeholder="Ваша оцінка" required> / {{ q.price }}<br>
                {% elif result.mark == 0 and not is_owner %}
                    не оцінено
                {% else %}
                    {{ result.mark }} / {{ q.price }}
                {% endif %}
            {% endif %}
        {% endfor %}
    </div>
    {% endfor %}
    
    {% if is_owner %}
        <div class="quiz-detail-submit-div">
            <input type="submit" value="Перевірено" class="quiz-send-button quiz-button">
        </div>
    {% endif %}

</form>
</div>

<script>
    window.addEventListener("load", function(event) {
        userAnswers = document.getElementsByName("userAnswer");
        
        for (let i = 0; i < userAnswers.length; i++) {
            userAnswer = userAnswers[i].value.split(", ");
            currentCheckbox = document.getElementById(`checkbox_${parseInt(userAnswer[1])}`);
            currentOption = document.getElementById(`option_${parseInt(userAnswer[1])}`);
            currentCheckbox.checked = true;
            
            if (userAnswer[0] === "True") {
                currentOption.classList.add("option-true");
            }
            else {
                currentOption.classList.add("option-false");
            }

            console.log(currentCheckbox);
        }
    });
</script>
{% endblock %}